export enum ContractStatus {
  WAITING_PROPOSAL = 'WAITING_PROPOSAL',
  NOT_GENERATED = 'NOT_GENERATED',
  CONTRACT_GENERATED = 'CONTRACT_GENERATED',
  EDITED_MANUALLY = 'EDITED_MANUALLY',
  SENT = 'SENT',
  SIGNED = 'SIGNED',
}